"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Sidebar from "../sidebar";

type Project = { id: string; name: string; clientName: string; dashboardData?: string };
type Account = { id: string; name: string; email: string; status: string; assigned?: boolean };
type LinkItem = { token: string; label: string; createdAt: string; expiresAt?: string; active: boolean };

function readLinks(project?: Project): LinkItem[] {
  try { const data = JSON.parse(project?.dashboardData || "{}"); return Array.isArray(data.permissionConfig?.shareLinks) ? data.permissionConfig.shareLinks : []; } catch { return []; }
}
function makeToken() { return crypto.randomUUID().replaceAll("-", ""); }

export default function PermissionsPage() {
  const [projects, setProjects] = useState<Project[]>([]); const [selectedId, setSelectedId] = useState(""); const [accounts, setAccounts] = useState<Account[]>([]);
  const [form, setForm] = useState({ name: "", email: "", password: "" }); const [linkLabel, setLinkLabel] = useState(""); const [linkExpiry, setLinkExpiry] = useState(""); const [links, setLinks] = useState<LinkItem[]>([]); const [editingLink, setEditingLink] = useState<string | null>(null); const [editLink, setEditLink] = useState({ label: "", expiresAt: "" });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const selected = useMemo(() => projects.find(project => project.id === selectedId), [projects, selectedId]);

  async function loadProjects() { setLoading(true); setError(""); try { const response = await fetch("/api/projects"); const data = await response.json(); if (!response.ok) throw new Error(data.error || "專案載入失敗"); const items = data.projects || []; setProjects(items); const saved = localStorage.getItem("kevin-active-project-id"); setSelectedId(items.some((item: Project) => item.id === saved) ? saved || "" : items[0]?.id || ""); } catch (cause) { setError(cause instanceof Error ? cause.message : "專案載入失敗"); } finally { setLoading(false); } }
  async function loadAccounts(projectId: string) { const response = await fetch(`/api/access/accounts?projectId=${encodeURIComponent(projectId)}`); const data = await response.json(); if (response.ok) setAccounts(data.accounts || []); else setError(data.error || "帳號載入失敗"); }
  useEffect(() => { fetch("/api/auth/me").then(response => response.ok ? response.json() : null).then(data => { if (data?.access?.kind !== "owner") { window.location.href = "/login"; return; } loadProjects(); }).catch(() => { window.location.href = "/login"; }); }, []);
  useEffect(() => { if (selected) { setLinks(readLinks(selected)); loadAccounts(selected.id); } }, [selected]);
  function chooseProject(id: string) { setSelectedId(id); localStorage.setItem("kevin-active-project-id", id); }
  async function createAccount(event: FormEvent) { event.preventDefault(); if (!selected) return; setSaving(true); setError(""); try { const response = await fetch("/api/access/accounts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, projectId: selected.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "帳號建立失敗"); setMessage(`已設定 ${data.account.email} 的查看帳號`); setForm({ name: "", email: "", password: "" }); await loadAccounts(selected.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "帳號建立失敗"); } finally { setSaving(false); } }
  async function toggleAccount(account: Account) { if (!selected) return; setSaving(true); setError(""); try { if (account.assigned) { const response = await fetch(`/api/access/accounts/${account.id}?projectId=${encodeURIComponent(selected.id)}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "移除失敗"); setMessage(`已移除 ${account.email} 的本專案權限`); } else { const response = await fetch("/api/access/accounts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: account.name, email: account.email, projectId: selected.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "加入失敗"); setMessage(`已將 ${account.email} 加入本專案`); } await loadAccounts(selected.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "權限更新失敗"); } finally { setSaving(false); } }
  async function saveLinks(next: LinkItem[], text: string) { if (!selected) return; setSaving(true); setError(""); let data: Record<string, unknown> = {}; try { data = JSON.parse(selected.dashboardData || "{}"); } catch { data = {}; } const oldConfig = (data.permissionConfig && typeof data.permissionConfig === "object") ? data.permissionConfig : {}; const response = await fetch(`/api/projects/${selected.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ dashboardData: { ...data, permissionConfig: { ...oldConfig, shareLinks: next } } }) }); const result = await response.json(); setSaving(false); if (!response.ok) { setError(result.error || "連結設定失敗"); return; } setLinks(next); setProjects(items => items.map(item => item.id === selected.id ? { ...item, dashboardData: JSON.stringify({ ...data, permissionConfig: { ...oldConfig, shareLinks: next } }) } : item)); setMessage(text); }
  function createLink() { saveLinks([...links, { token: makeToken(), label: linkLabel.trim() || "未命名查看連結", createdAt: new Date().toISOString(), expiresAt: linkExpiry || undefined, active: true }], "已建立唯讀連結"); setLinkLabel(""); setLinkExpiry(""); }
  function deleteLink(value: string) { if (window.confirm("確定要刪除這個唯讀連結嗎？刪除後無法再開啟。")) saveLinks(links.filter(item => item.token !== value), "已刪除唯讀連結"); }
  function startEditLink(link: LinkItem) { setEditingLink(link.token); setEditLink({ label: link.label, expiresAt: link.expiresAt || "" }); }
  function saveEditedLink(value: string) { const label = editLink.label.trim() || "未命名查看連結"; saveLinks(links.map(item => item.token === value ? { ...item, label, expiresAt: editLink.expiresAt || undefined } : item), "唯讀連結設定已儲存"); setEditingLink(null); }
  async function copyLink(value: string) { await navigator.clipboard?.writeText(`${location.origin}/shared/${value}`); setMessage("連結已複製"); }

  return <main className="app-shell"><header className="topbar"><a className="brand brand-link" href="/"><span className="brand-mark">K</span><span><strong>Kevin SEO Decision Dashboard</strong><small>SEO＋AI Search 投資決策儀表板</small></span></a></header><Sidebar active="permissions" reviewMode /><div className="workspace sidebar-workspace permissions-page">
    <section className="project-heading"><div><p className="kicker">ACCESS MANAGEMENT · M03</p><h1>權限管理</h1><p>設定窗口登入帳號，並指定他可以純瀏覽的專案。</p></div></section>
    {error && <div className="project-error" role="alert">{error}</div>}{message && <div className="permissions-message" role="status">{message}</div>}
    <section className="permission-project-bar panel"><label><span>目前設定專案</span><select value={selectedId} onChange={event => chooseProject(event.target.value)} disabled={loading}><option value="">{loading ? "載入專案中" : "請選擇專案"}</option>{projects.map(project => <option value={project.id} key={project.id}>{project.clientName}｜{project.name}</option>)}</select></label><small>帳號建立後，可以在其他專案重複指派同一個 Email。</small></section>
    {selected && <div className="permissions-grid"><section className="panel permission-card"><div className="settings-head"><div><p className="kicker">COLLABORATOR ACCOUNT</p><h2>設定窗口帳號</h2><p>新窗口建立 Email 與密碼；已建立的窗口可直接勾選加入本專案。</p></div><span className="permission-badge">純瀏覽</span></div><form className="permission-form" onSubmit={createAccount}><input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="窗口名稱，例如：Shirley" aria-label="窗口名稱" /><input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} placeholder="登入 Email" aria-label="登入 Email" /><input required minLength={8} type="password" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} placeholder="設定密碼（至少 8 碼）" aria-label="設定密碼" /><button className="save-button" type="submit" disabled={saving}>建立新帳號</button></form><div className="permission-existing"><h3>已建立的窗口帳號</h3>{accounts.length === 0 ? <p className="permission-empty">目前尚未建立窗口帳號。</p> : accounts.map(account => <label key={account.id} className="permission-account-check"><input type="checkbox" checked={Boolean(account.assigned)} onChange={() => toggleAccount(account)} disabled={saving || account.status !== "active"} /><span><strong>{account.name}</strong><small>{account.email}｜{account.status === "active" ? "可登入" : "已停用"}</small></span></label>)}</div><p className="permission-note">勾選後，窗口登入即可看到本專案；同一個窗口可以被勾選到多個專案。</p></section>
      <section className="panel permission-card"><div className="settings-head"><div><p className="kicker">READ-ONLY LINKS</p><h2>專案唯讀連結</h2><p>提供給客戶主管等臨時查看者，不需要建立帳號。</p></div></div><div className="permission-form link-form"><input value={linkLabel} onChange={event => setLinkLabel(event.target.value)} placeholder="連結用途，例如：客戶主管查看" aria-label="連結用途" /><label className="link-expiry"><span>到期日</span><input type="date" value={linkExpiry} min={new Date().toISOString().slice(0, 10)} onChange={event => setLinkExpiry(event.target.value)} aria-label="唯讀連結到期日" /></label><button className="save-button" type="button" onClick={createLink} disabled={saving}>產生連結</button></div><div className="permission-list">{links.length === 0 ? <p className="permission-empty">目前尚未建立唯讀連結。</p> : links.map(link => <article key={link.token}>{editingLink === link.token ? <div className="permission-link-edit"><label><span>連結名稱</span><input value={editLink.label} onChange={event => setEditLink({ ...editLink, label: event.target.value })} /></label><label><span>有效日期</span><input type="date" value={editLink.expiresAt} min={new Date().toISOString().slice(0, 10)} onChange={event => setEditLink({ ...editLink, expiresAt: event.target.value })} /><small>清空日期＝永久有效</small></label></div> : <div><strong>{link.label}</strong><small>{link.active ? "啟用中" : "已停用"}｜{link.expiresAt ? `到期：${link.expiresAt}` : "永久有效"}｜建立於 {link.createdAt.slice(0, 10)}</small></div>}<div className="permission-actions">{editingLink === link.token ? <><button type="button" onClick={() => saveEditedLink(link.token)} disabled={saving}>儲存</button><button type="button" onClick={() => setEditingLink(null)} disabled={saving}>取消</button></> : <><button type="button" onClick={() => startEditLink(link)} disabled={saving}>修改</button><button type="button" onClick={() => copyLink(link.token)} disabled={!link.active}>複製</button>{link.active && <button type="button" onClick={() => saveLinks(links.map(item => item.token === link.token ? { ...item, active: false } : item), "已停用唯讀連結")} disabled={saving}>停用</button>}<button type="button" onClick={() => deleteLink(link.token)} disabled={saving}>刪除</button></>}</div></article>)}</div><p className="permission-note">到期後連結會自動失效；刪除後無法恢復。帳號登入適合固定合作窗口，連結適合單次分享。</p></section></div>}
  </div></main>;
}
